USPesos/urls.py
from django.contrib import admin
from django.urls import path, include
from user.views import login2

urlpatterns = [
    path('', login2 ,name='login_redirect'),
    path('user/', include('user.urls')),
    path('alunos/', include('alunos.urls')),
    path('professores/', include('professores.urls')),
    path('secretaria/', include('secretaria.urls')),
    path('user/', include('django.contrib.auth.urls')),
    path('admin/', admin.site.urls),
    path('api/v1/', include('api.urls')),
]

api/urls.py
from django.urls import path
from .views import ExercicioList, ExercicioDetail

urlpatterns = [
    path('exercicios/<int:pk>/', ExercicioDetail.as_view()),
    path('exercicios/', ExercicioList.as_view())
]

secretaria/urls.py
from django.urls import path
from . import views

# URLs dos usuários

app_name = 'secretaria'

urlpatterns = [
    path('home/',views.home, name = 'home'),
    path('dados/',views.dados, name = 'dados'),
]

user/urls.py
from django.urls import path
from . import views

# URLs dos usuários

app_name = 'user'

urlpatterns = [
    path('cadastro/',views.register, name='cadastro'),
    path('cadastro_aluno/',views.Aluno_register.as_view(), name='cadastro_aluno'),
    path('cadastro_professor/',views.Professor_register.as_view(), name='cadastro_professor'),
    path('home/',views.home, name = 'home'),
]

secretaria/models.py
from django.db import models

# Create your models here.

secretaria/views.py
from django.shortcuts import render
from django.contrib.auth.decorators import login_required
from user.decorators import admin_required
from django.utils.decorators import method_decorator
from professores.models import Professor, Aluno, Treino, Aula, Modalidade
from user.models import Secretario
from alunos.models import Sessao
import datetime
from datetime import date

# Create your views here.
@login_required
@admin_required
def home(request):
    context = {}
    return render(request, 'secretaria/home.html', context = context)

@login_required
@admin_required
def dados(request):
    alunos = Aluno.objects.all()

    idades = 0
    for aluno in alunos:
        idade = date.today().year - aluno.nascimento.year
        idades += idade

    if len(alunos) != 0:
        media_idades = round(idades/len(alunos), 2)
    else:
        media_idades = 0

    professores = Professor.objects.all()

    treinos = []
    for professor in professores:
        treino = Treino.objects.filter(professor = professor).all()
        treinos.append((professor.user.name, treino.count()))

    aulas_por_modalidade = []
    modalidades = Modalidade.objects.all()
    for modalidade in modalidades:
        aulas = Aula.objects.filter(modalidade = modalidade).all()
        numero_de_aulas = aulas.count()
        aulas_por_modalidade.append((modalidade.nome, numero_de_aulas))

    professor_do_mes = professores.last()
    a = 0

    aulas_por_professor = []
    for professor in professores:
        aulas = Aula.objects.filter(professor = professor).all()
        numero_de_aulas = aulas.count()
        if numero_de_aulas > a:
            professor_do_mes = professor
            a = numero_de_aulas

        aulas_por_professor.append((professor.user.name, numero_de_aulas))

    secretarios = Secretario.objects.all()
    total_secretarios = secretarios.count()

    ultimo_aluno_cadastrado = alunos.last()

    ultimo_professor_cadastrado = professores.last()


    alunos_por_secretarios = []
    for secretario in secretarios:
        alunos_cadastrados = alunos.filter(secretario = secretario)
        alunos_por_secretarios.append((secretario.name, alunos_cadastrados.count()))

    sessoes = Sessao.objects.all()
    tempo_sessao = 0
    numero_sessoes = 0
    if sessoes and sessoes.first().tempo_fim:
        for sessao in sessoes:
            if sessao.tempo_fim:
                tempo_sessao += (sessao.tempo_fim.hour - sessao.tempo_inicio.hour)*60 + sessao.tempo_fim.minute - sessao.tempo_inicio.minute
                numero_sessoes += 1
        media_de_tempos = round(tempo_sessao/numero_sessoes, 2)

    else:
        media_de_tempos = 0

    


    context = {
        'alunos' : alunos,
        'media_idades' : media_idades,
        'professores' : professores,
        'treinos' : treinos,
        'aulas' : aulas_por_modalidade,
        'aulas_prof' : aulas_por_professor,
        'secretarios' : total_secretarios,
        'ultimo_aluno' : ultimo_aluno_cadastrado,
        'ultimo_professor' : ultimo_professor_cadastrado,
        'alunos_por_secretarios' : alunos_por_secretarios,
        'media_tempos' : media_de_tempos,
        'professor_do_mes' : professor_do_mes,
        }
    return render(request, 'secretaria/dados.html', context = context)

secretaria/templates/secretaria/dados.html
{% extends 'base.html' %}

{% block content %}

<div class="p1">

<h1>Dados</h1><br>

<div id="container-dados">

    <div id="bloco-container-dados">
        <h2> Alunos </h2><br>

        <p><b> Total de alunos: </b> {{ alunos.count }} </p>
        <p><b> Tempo médio na academia: </b> {{ media_tempos }} minutos </p>
        <p><b> Média de idades: </b> {{ media_idades }} anos </p>
    </div>
    
    <div id="bloco-container-dados">
        <h2> Professores </h2><br>

        <p><b> Total de professores: </b> {{ professores.count }} </p>
        <p><b> Treinos por professor: </b>  </p>

        {% for treino in treinos %}

        <p>{{ treino }}</p>

        {% endfor %}


        <p><b> Aulas por modalidade: </b></p>

        {% for aula in aulas %}

        <p>{{ aula }}</p>

        {% endfor %}

        <p><b> Aulas por professor: </b></p>

        {% for aula in aulas_prof %}

        <p>{{ aula }}</p>

        {% endfor %}
    </div>
    
    <div id="bloco-container-dados">
        <h2> Secretaria </h2><br>

        <p><b> Total de secretários:</b> {{ secretarios }} </p>

        <p><b> Aluno mais recente:</b> {{ ultimo_aluno }} </p>

        <p><b> Professor mais recente:</b> {{ ultimo_professor }} </p>

        <p><b> Professor do mês:</b> {{ professor_do_mes.nome }}</p>
            <img src="{{ professor_do_mes.urlfoto }} " alt="Foto professor do mês" id="foto-perfil">


        <p><b> Alunos por secretário: </b></p>

        {% for secretario in alunos_por_secretarios %}

        <p>{{ secretario }}</p>

        {% endfor %}
    </div>
</div>

<br>
<br>

<a href="{% url 'secretaria:home' %}" class="btn btn-secondary">Voltar</a>
    
<br>
<br>

</div>

{% endblock content %}

secretaria/templates/secretaria/home.html
{% extends 'base.html' %}

{% block content %}

<div class="p1">

<h1>Secretaria</h1>

<div id="container-home-secretaria">

    <div style="width: 10px; height: 10px;"></div>
  
      <a href="{% url 'user:cadastro_aluno' %}" id="foto-container-secretaria">
          <div class="card bg-dark text-white">
          <img src="/static/cadastro_aluno.jpg" class="d-block w-100 brilho-50" alt="Cadastro aluno">
          <div class="card-img-overlay">
            <h2 class="card-title text-center">Cadastro de aluno</h2>
          </div>
        </div>
      </a>
  
      <div style="width: 10px;"></div>
  
      <a href="{% url 'user:cadastro_professor' %}" id="foto-container-secretaria">
        <div class="card bg-dark text-white">
          <img src="/static/cadastro_professor.jpg" class="d-block w-100 brilho-30" alt="Cadastro professor">
          <div class="card-img-overlay">
              <h2 class="card-title text-center">Cadastro de professor</h2>
          </div>
        </div>
      </a>
  
      <div style="width: 10px;"></div>

      <a href="{% url 'secretaria:dados' %}" id="foto-container-secretaria">
        <div class="card bg-dark text-white">
          <img src="/static/analise_dados.jpg" class="d-block w-100 brilho-30" alt="Dados">
          <div class="card-img-overlay">
              <h2 class="card-title text-center">Dados</h2>
          </div>
        </div>
      </a>
  
      <div style="width: 10px;"></div>
        
  </div>

</div>

{% endblock content %}