USPesos/urls.py
from django.contrib import admin
from django.urls import path, include
from user.views import login2

urlpatterns = [
    path('', login2 ,name='login_redirect'),
    path('user/', include('user.urls')),
    path('alunos/', include('alunos.urls')),
    path('professores/', include('professores.urls')),
    path('secretaria/', include('secretaria.urls')),
    path('user/', include('django.contrib.auth.urls')),
    path('admin/', admin.site.urls),
    path('api/v1/', include('api.urls')),
]

api/urls.py
from django.urls import path
from .views import ExercicioList, ExercicioDetail

urlpatterns = [
    path('exercicios/<int:pk>/', ExercicioDetail.as_view()),
    path('exercicios/', ExercicioList.as_view())
]

user/urls.py
from django.urls import path
from . import views

# URLs dos usuários

app_name = 'user'

urlpatterns = [
    path('cadastro/',views.register, name='cadastro'),
    path('cadastro_aluno/',views.Aluno_register.as_view(), name='cadastro_aluno'),
    path('cadastro_professor/',views.Professor_register.as_view(), name='cadastro_professor'),
    path('home/',views.home, name = 'home'),
]

templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="pt-br">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>
        {% block title %}{% endblock %} | USPesos
    </title>
    <link href="https://fonts.googleapis.com/css?family=Inter&display=swap" rel="stylesheet" />
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <link rel="stylesheet" type="text/css" href="{% static 'estilo.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'estilo2.css' %}">
    <link rel="icon" href="{% static 'favicon_uspesos.png' %}">
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.2/dist/umd/popper.min.js" integrity="sha384-IQsoLXl5PILFhosVNubq5LC7Qb9DXgDA9i+tQ8Zj3iwWAwPtgFTxbJ8NT4GN1R8p" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.min.js" integrity="sha384-cVKIPhGWiC2Al4u+LWgxfKTRIcfu0JTxR+EQDz/bgldoEyl4H0zUF0QKbrJ0EcQF" crossorigin="anonymous"></script>

</head>

<body id="imagem-fundo-login">
    <header id="cabecalho-principal">
        <a href="">
            <p></p>
        </a>
        <nav id="navegacao-principal">
            <ul>
                <li><a href="{% url 'user:home' %}"><img src="/static/logo_uspesos_2.png" id="logo-header"></a></li>
                {% if user.is_authenticated %}
                    {% if user.is_aluno or user.is_professor %}
                    <li><h6 style="color: black;"><b id="texto-header">Logado(a) como: {{user.name}}</b></h6></li>
                    <li><a href="{% url 'logout' %}?next=/user/login/" id="texto-header">Log out</a></li>
                    {% else %}
                    <li><h6 style="color: black;" id="texto-header"><b id="texto-header">Logado como secretaria</b></h6></li>
                    <li><a href="{% url 'logout' %}?next=/user/login/" id="texto-header">Log out</a></li>
                    {% endif %}
                {% else %}
                <li><h6 style="color: black;"><b id="texto-header">Bem-vindo(a) ao USPesos!</b></h6></li>

                {% endif %}
            </ul>
        </nav>

    </header>
    <div style="height: 70px;"></div>
    <main id="conteiner-principal">
        {% block content %}
        {% endblock content %}
    </main>

    <br>
    <br>

    <footer id="rodape-principal">
        <p>
            <small>USPesos Copyright © 2022</small>
        </p>
    </footer>
</body>

</html>