USPesos/urls.py
from django.contrib import admin
from django.urls import path, include
from user.views import login2

urlpatterns = [
    path('', login2 ,name='login_redirect'),
    path('user/', include('user.urls')),
    path('alunos/', include('alunos.urls')),
    path('professores/', include('professores.urls')),
    path('secretaria/', include('secretaria.urls')),
    path('user/', include('django.contrib.auth.urls')),
    path('admin/', admin.site.urls),
    path('api/v1/', include('api.urls')),
]

alunos/urls.py
from django.urls import path
from . import views


# URLs dos usuários

app_name = 'alunos'

urlpatterns = [
    path('home/',views.home, name = 'home'),
    path('perfil/',views.perfil, name = 'perfil'),
    path('editarperfil/',views.editarperfil, name = 'editarperfil'),
    path('meutreino/',views.meutreino, name = 'meutreino'),
    path('novotreino/',views.TreinoCreateView.as_view(), name = 'novotreino'),
    path('aulas/',views.aulas, name = 'aulas'),
    path('aulas/<int:pk>/insc',views.inscricao, name = 'inscricao'),
    path('aulas/<int:pk>/desinsc',views.desinscricao, name = 'desinscricao'),
    path('home/iniciar_sessao',views.iniciar_sessao, name = 'iniciar_sessao'),
    path('home/terminar_sessao',views.terminar_sessao, name = 'terminar_sessao'),
]

api/urls.py
from django.urls import path
from .views import ExercicioList, ExercicioDetail

urlpatterns = [
    path('exercicios/<int:pk>/', ExercicioDetail.as_view()),
    path('exercicios/', ExercicioList.as_view())
]

alunos/models.py
from django.db import models
from user.models import Aluno

class Sessao(models.Model):

    tempo_inicio = models.TimeField("Início da sessão", blank = True)
    tempo_fim = models.TimeField("Fim da sessão", null = True)
    aluno = models.ForeignKey(Aluno, on_delete= models.CASCADE)

alunos/forms.py
from django import forms
from django.forms import ModelForm
from professores.models import Treino
from user.models import Aluno
from django.db import transaction

# class FormataComentario(forms.TextInput):
#     class = 'form-control'

class TreinoForm(ModelForm):
    class Meta:
        model = Treino
        fields = [
            'nivel',
            'comentario',
            'professor',
        ]
        widgets = {
            'nivel': forms.Select(choices = ((1, 'fácil'), (2, 'médio'), (3, 'difícil'))),
        }

class EditarPerfilForm(ModelForm):
    class Meta:
        model = Aluno
        fields = [
            'email',
            'telefone',
            'endereco',
            'urlfoto',
            'altura',
            'peso',
            'bracos',
            'coxa',
            'peitoral',
            'cinturaescapular',
            'percentualgordura',

        ]

        labels = {
            'email':'Email',
            'telefone':'Telefone',
            'endereco':'Endereço',
            'urlfoto':'Url da foto',
            'altura':'Altura',
            'peso':'Peso',
            'bracos':'Braços',
            'coxa':'Coxa',
            'peitoral':'Peitoral',
            'cinturaescapular':'Cintura escapular',
            'percentualgordura':'Percentual de gordura',
        }

        widgets = {
            'email': forms.EmailInput(attrs={'class':'form-control'}),
            'telefone': forms.TextInput(attrs={'class':'form-control'}),
            'endereco': forms.TextInput(attrs={'class':'form-control'}),
            'urlfoto': forms.TextInput(attrs={'class':'form-control'}),
            'altura': forms.NumberInput(attrs={'class':'form-control'}),
            'peso': forms.NumberInput(attrs={'class':'form-control'}),
            'bracos': forms.NumberInput(attrs={'class':'form-control'}),
            'coxa': forms.NumberInput(attrs={'class':'form-control'}),
            'peitoral': forms.NumberInput(attrs={'class':'form-control'}),
            'cinturaescapular': forms.NumberInput(attrs={'class':'form-control'}),
            'percentualgordura': forms.NumberInput(attrs={'class':'form-control'}),
        }

alunos/views.py
from django.shortcuts import render, redirect
from user.models import Aluno, User
from professores.models import Treino, Aula, Itemtreino, Inscricao
from .models import Sessao
from django.views import generic
from alunos.forms import TreinoForm, EditarPerfilForm
from django.http import HttpResponseRedirect
from django.urls import reverse
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from user.decorators import aluno_required
from django.utils.decorators import method_decorator
from datetime import datetime, date, timedelta

# Create your models here.

@login_required
@aluno_required
def home(request):

    ultima_sessao = Sessao.objects.filter(aluno = Aluno.objects.get(user = request.user)).last()

    if request.user.is_authenticated:
        aluno = Aluno.objects.get(user=request.user)
        context = {'aluno' : aluno,
        'ultima_sessao' : ultima_sessao,
        }
    return render(request, 'alunos/home.html', context = context)

def iniciar_sessao(request):

    context = {}

    tempo_inicio = datetime.now()
    aluno = Aluno.objects.get(user = request.user)
    sessao = Sessao.objects.create(tempo_inicio = tempo_inicio, aluno = aluno)
    sessao.save()

    return redirect('alunos:home')      

def terminar_sessao(request):

    context = {}

    tempo_fim = datetime.now()
    aluno = Aluno.objects.get(user = request.user)
    sessao = Sessao.objects.filter(aluno = aluno).last()
    sessao.tempo_fim = tempo_fim
    sessao.save()

    return redirect('alunos:home')       


@login_required
@aluno_required
def perfil(request):

    if request.user.is_authenticated:
        aluno = Aluno.objects.get(user=request.user)
        context = {'aluno' : aluno}

    return render(request, 'alunos/perfil.html', context = context)

# class PerfilUpdateView(generic.UpdateView):
#     form_class = EditarPerfilForm
#     model = Aluno
#     template_name = 'alunos/editarperfil.html'

@login_required
@aluno_required
def editarperfil(request):
    if request.user.is_authenticated:
        aluno = Aluno.objects.get(user=request.user)
        # user = User.objects.get(user=request)

        if request.method == "POST":
            form = EditarPerfilForm(request.POST)

            if form.is_valid():
                # aluno.user.name = request.POST['name']
                aluno.email = form.cleaned_data['email']
                # aluno.nascimento = form.cleaned_data['nascimento']
                aluno.telefone = form.cleaned_data['telefone']
                aluno.endereco = form.cleaned_data['endereco']
                aluno.urlfoto = form.cleaned_data['urlfoto']
                aluno.altura = form.cleaned_data['altura']
                aluno.peso = form.cleaned_data['peso']
                aluno.bracos = form.cleaned_data['bracos']
                aluno.coxa = form.cleaned_data['coxa']
                aluno.peitoral = form.cleaned_data['peitoral']
                aluno.cinturaescapular = form.cleaned_data['cinturaescapular']
                aluno.percentualgordura = form.cleaned_data['percentualgordura']

                # aluno.user.save()
                aluno.save()
                return HttpResponseRedirect(reverse('alunos:perfil'))

        else:
            form = EditarPerfilForm(
            initial={
                'email': aluno.email,
                # 'nascimento': aluno.nascimento,
                'telefone': aluno.telefone,
                'endereco':aluno.endereco,
                'urlfoto':aluno.urlfoto,
                'altura':aluno.altura,
                'peso':aluno.peso,
                'bracos':aluno.bracos,
                'coxa':aluno.coxa,
                'peitoral':aluno.peitoral,
                'cinturaescapular':aluno.cinturaescapular,
                'percentualgordura':aluno.percentualgordura,
            })

        context = {'aluno' : aluno, 'form': form}
        return render(request, 'alunos/editarperfil.html', context = context)

@login_required
@aluno_required
def meutreino(request):
    aluno = Aluno.objects.get(user=request.user)
    treino = Treino.objects.filter(aluno = aluno).filter(criado = True).last()
    treino_vigente = Treino.objects.filter(aluno = aluno).filter(criado = False).last()
    context={}

    if treino and treino_vigente:
        itenstreino = Itemtreino.objects.filter( treino = treino).all()
        context = {
            'treino' : treino,
            'itenstreino' : itenstreino,
            'treino_vigente' : treino_vigente,
            }

    elif treino:
        itenstreino = Itemtreino.objects.filter( treino = treino).all()
        context = {
            'treino' : treino,
            'itenstreino' : itenstreino,
            }

    elif treino_vigente:
        context = {
            'treino' : treino,
            'treino_vigente' : treino_vigente,
            }

    return render(request, 'alunos/meutreino.html', context = context)

@method_decorator([login_required, aluno_required], name='dispatch')
class TreinoCreateView(generic.CreateView):
    model = Treino
    form_class = TreinoForm
    template_name = 'alunos/novotreino.html'
    success_url = '/alunos/meutreino/'

    def form_valid(self, form):
        treino = form.save(commit=False)
        treino.aluno = Aluno.objects.get(user = self.request.user)
        treino.save()
        return redirect('alunos:meutreino')

@login_required
@aluno_required
def aulas(request):
    aulas = Aula.objects.filter(visivel = True).all()
    aluno = Aluno.objects.get(user = request.user)
    aulas_hoje = Aula.objects.filter(visivel = True, dia = date.today())
    aulas_amanha = Aula.objects.filter(visivel = True, dia = date.today() + timedelta(days=1))
    inscricao = Inscricao.objects.all().filter(alunos = aluno)


    context = {
        "aulas" : aulas,
        "aluno" : aluno,
        "aulas_hoje" : aulas_hoje,
        "aulas_amanha" : aulas_amanha,
        "inscricao" : inscricao,
    }

    return render(request, 'alunos/aulas.html', context = context)

@login_required
@aluno_required
def inscricao(request, pk):

    aluno = Aluno.objects.get(user = request.user)
    aula = Aula.objects.get( pk = pk )
    inscricao = Inscricao.objects.get(aula = aula)

    if  int(inscricao.alunos.count()) < int(aula.vagas) and not Inscricao.objects.filter(aula = aula, alunos = aluno).all():

        inscricao.alunos.add(aluno)
        inscricao.save()
        aula.inscritos += 1
        aula.save()

        messages.success(request, 'Você se inscreveu na aula com sucesso!')
    
    else:

        messages.warning(request, 'Você já está inscrito ou a turma está cheia!')

    return redirect('alunos:aulas')

@login_required
@aluno_required
def desinscricao(request, pk):
    
    aluno = Aluno.objects.get(user = request.user)
    aula = Aula.objects.get( pk = pk )
    inscricao = Inscricao.objects.get(aula = aula)

    if Inscricao.objects.filter(aula = aula, alunos = aluno).all():
        inscricao.alunos.remove(aluno)
        inscricao.save()
        aula.inscritos -= 1
        aula.save()

    return redirect('alunos:aulas')

alunos/templates/alunos/aulas.html
{% extends 'base.html' %}

{% block title %}
Aulas
{% endblock title %}

{% block content %}

<div id = "tp">
    <div class = "p1"><h1><p style="color: white;">Aulas</p></h1></div>  
</div>

<div class = "p1">


<div id="container-aulas">
    <div id="texto-aulas" style="background-color: rgba(255, 255, 255, 0.200);">
        <h4 style="background-color: rgb(254, 185, 47); text-align: center;">AULAS DE HOJE</h4>
        {% if aulas_hoje %}
        {% for aula in aulas_hoje %}
            <ul class="p1">
                <li> <u><b>Modalidade:</b></u> {{ aula.modalidade.nome }} </li>
                <li> <u><b>Descrição:</b></u> {{ aula.modalidade.descricao }} </li>
                <li> <u><b>Professor:</b></u> {{ aula.professor }} </li>
                <li> <u><b>Capacidade:</b></u>  {{ aula.inscritos }} / {{ aula.vagas }}</li>
                <li> <u><b>Horário:</b></u> {{ aula.hora }} </li>
                <li> <u><b>Duração:</b></u> {{ aula.duracao }} </p>

                <div class="d-grid gap-2 col-6 mx-auto">
                    <a href = "{% url 'alunos:inscricao' aula.pk %}" class="btn btn-warning"> Inscreva-se </a>
                </div>

                <br>
                
                <div class="d-grid gap-2 col-6 mx-auto">
                    <a href = "{% url 'alunos:desinscricao' aula.pk %}" class="btn btn-warning" style="background-color: rgb(167, 123, 33); border-color: rgb(167, 123, 33);"> Desinscreva-se </a>
                </div>
            </ul>
            <br>
            <br>
            
        {% endfor %}
    
    {% else %}
    
    <p class="p1">Não há nenhuma aula hoje.</p> <br>
    
    {% endif %}
    </div>


<div style="width: 10px;"></div>


    <div id="texto-aulas" style="background-color: rgba(255, 255, 255, 0.200);">

    
<h4 style="background-color: rgb(254, 185, 47); text-align: center;">AULAS DE AMANHÃ</h4>
{% if aulas_amanha %}
        {% for aula in aulas_amanha %}
            
        <ul class="p1">
            <li> <u><b>Modalidade:</b></u> {{ aula.modalidade.nome }} </li>
            <li> <u><b>Descrição:</b></u> {{ aula.modalidade.descricao }} </li>
            <li> <u><b>Professor:</b></u> {{ aula.professor }} </li>
            <li> <u><b>Capacidade:</b></u>  {{ aula.inscritos }} / {{ aula.vagas }}</li>
            <li> <u><b>Horário:</b></u> {{ aula.hora }} </li>
            <li> <u><b>Duração:</b></u> {{ aula.duracao }} </p>
            <div class="d-grid gap-2 col-6 mx-auto">
                <a href = "{% url 'alunos:inscricao' aula.pk %}" class="btn btn-warning"> Inscreva-se </a>
            </div>
            
            <br>

            <div class="d-grid gap-2 col-6 mx-auto">
                <a href = "{% url 'alunos:desinscricao' aula.pk %}" class="btn btn-warning" style="background-color: rgb(167, 123, 33); border-color: rgb(167, 123, 33);"> Desinscreva-se </a>
            </div>
        </ul> 
        <br>
        <br>


            
        {% endfor %}

    {% else %}

    <p class="p1">Não há nenhuma aula amanhã.</p>

    {% endif %}
    </div>

    <div style="width: 10px;"></div>


</div>

<br>
<br>

<a href="{% url 'alunos:home' %}" class="btn btn-secondary">Voltar</a>
    
<br>

{% endblock content %}

alunos/templates/alunos/editarperfil.html
{% extends 'base.html' %}

{% block title %}
EditarPerfil
{% endblock title %}

{% block content %}

<div class="p1">
    <h2>Atualizar Dados do Perfil de {{ user.name }}</h2><br>
</div>
<div class="p3">
    <form method="POST" action="{% url 'alunos:editarperfil' %}">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit" class="btn btn-primary">Atualizar</button>
    </form>
</div>

<br>
<br>

<a href="{% url 'alunos:perfil' %}" class="btn btn-secondary">Voltar</a>

<br>
<br>
{% endblock content %}

alunos/templates/alunos/home.html
{% extends 'base.html' %}

{% block title %}
Home
{% endblock title %}

{% block content %}

<div class="d-flex justify-content-around">
  <div class = "p1"><h1>Olá, {{ user.name }}, qual a boa de hoje?</h1></div>
  <div style="width: 55%"></div>
  <div class = "p2"><a href="{% url 'alunos:perfil' %}" class="text-decoration-none">
    <div class="text-center">
        <img src="{{ aluno.urlfoto }}" alt="Foto de perfil" id="foto-perfil">
        <br>
        <p>{{ user.name }}</p>
    </div>
    </a>
  </div>
</div>

<br>

<div id="container-home">

  <div style="width: 10px; height: 10px;"></div>

  <div style="width: 10px; height: 10px;"></div>
    <a href="{% url 'alunos:meutreino' %}" id="foto-container">
        <div class="card bg-dark text-white">
        <img src="/static/meu_treino.jpg" class="d-block w-100 brilho-50" alt="Meu treino">
        <div class="card-img-overlay">
          <h1 class="card-title text-center">Meu Treino</h1>
        </div>
      </div>
    </a>

    <div style="width: 10px;"></div>

    <a href="{% url 'alunos:aulas' %}" id="foto-container">
      <div class="card bg-dark text-white">
        <img src="/static/aulas.webp" class="d-block w-100 brilho-30" alt="Aulas">
        <div class="card-img-overlay">
            <h1 class="card-title text-center">Aulas</h1>
        </div>
      </div>
    </a>

    <div style="width: 10px;"></div>
      
</div>
<br>
<br>

<article style="text-align: center;">
  <div class="grid-sessao">
      <div class="bx1"><p>ULTIMA SESSAO</p></div>
      {% if ultima_sessao.tempo_inicio %}
        <div class="bx2">INICIO<br><p style="color: rgb(16, 174, 66);">{{ ultima_sessao.tempo_inicio }}</p></div>
      {% else %}
        <div class="bx2">INICIO<br><p style="color: rgb(16, 174, 66);">---</p></div>
      {% endif %}

      {% if ultima_sessao.tempo_fim %}
        <div class="bx3">FIM<br><p style="color: red;">{{ ultima_sessao.tempo_fim }}</p></div>
      {% else %}
        <div class="bx3">FIM<br><p style="color: red;">---</p></div>
      {% endif %}
  </div>
</article>

<br>

{% if ultima_sessao.tempo_fim or not ultima_sessao %}

<div class="d-grid gap-2 col-6 mx-auto">
  <a href="{% url 'alunos:iniciar_sessao' %}" class="btn btn-success">Check-in</a>
</div>

{% else %}

<div class="d-grid gap-2 col-6 mx-auto">
  <a href="{% url 'alunos:terminar_sessao' %}" class="btn btn-danger">Check-out</a>
</div>
{% endif %}

{% endblock %}

alunos/templates/alunos/meutreino.html
{% extends 'base.html' %}

{% block title %}
Meu Treino
{% endblock title %}

{% block content %}

<div class="d-flex justify-content-around">
    <div class = "p1"><h1>Meu treino</h1></div>
    <div style="width: 70%"></div>
    <div class = "p2"><a href="{% url 'alunos:novotreino' %}" class="btn btn-primary" style="height:auto;"><b>Novo treino</b></a></div>
</div>

<div>
<br>
<div class = "p1">
{% if itenstreino and treino_vigente %}
    <div class = "lista-exercicio">
    {% for item in itenstreino %}
        <div class = "card-exercicio">
            <p> Exercício: {{ item.exercicio }}</p>
            <p> Carga: {{ item.carga }} Kg</p>
            <p> Repetições: {{ item.repeticao }}</p>
            <p><img src="{{ item.exercicio.urlfoto }}" alt="Foto do exercicio" id="foto-exercicio"> </p>
        </div>
        <br>
    {% endfor %}
    </div>

<p> Seu novo treino está sendo montado pelo professor {{ treino_vigente.professor.user.name }}. Por favor aguarde.  </p>

{% elif itenstreino %}
    <div class = "lista-exercicio">
    {% for item in itenstreino %}
        <div class = "card-exercicio">
            <p> Exercício: {{ item.exercicio }}</p>
            <p> Carga: {{ item.carga }} Kg </p>
            <p> Repetições: {{ item.repeticao }}</p>
            <p><img src="{{ item.exercicio.urlfoto }}" alt="Foto do exercicio" id="foto-exercicio"> </p>
        </div>
        <br>
    {% endfor %}
    </div>
<br>
<p>Quer um novo treino? <a href="{% url 'alunos:novotreino' %}">Requistar novo treino</a></p>

{% elif treino_vigente %}

    <p> Seu treino está sendo montado pelo professor {{ treino_vigente.professor.user.name }}. Por favor aguarde.  </p>

{% else %}

    <p>Não existe treino vigente. <a href="{% url 'alunos:novotreino' %}">Solicite já um treino</a></p>

{% endif %}
</div>
</div>

<br>

<a href="{% url 'alunos:home' %}" class="btn btn-secondary">Voltar</a>
    
<br>

{% endblock %}

alunos/templates/alunos/novotreino.html
{% extends 'base.html' %}

{% block content %}

<div id = "tp">
    <div class = "p1"><h1><p style="color: white;">Solicitar Treino</p></h1></div>  
</div>

<div class = "p3">
<form method="POST" action="{% url 'alunos:novotreino' %}">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit" class="btn btn-primary">Requisitar</button>
</form>

</div>    

<br>
<br>
<a href="{% url 'alunos:meutreino' %}" class="btn btn-secondary">Voltar</a>

{% endblock %}

alunos/templates/alunos/perfil.html
{% extends 'base.html' %}

{% block title %}
Perfil
{% endblock title %}

{% block content %}
<div class="d-flex justify-content-around">
    <div class = "p1"><h1>Perfil do aluno</h1></div>
    <div style="width: 60%"></div>
    <div class = "p2"><a href="{% url 'alunos:editarperfil' %}" class="btn btn-primary" style="height: auto;"><b>Atualizar</b></a></div>
</div>
    <br>

    <div class = "cperfil">
        <img src="{{ aluno.urlfoto }}" alt="Foto de perfil">
        <div class = "c1"><h2><p style="color: white;">{{ user.name }}</p></h2></div>
    </div>
    <br>
    <div class = "perfil">    
        <ul>
            <b>CPF:</b> {{ aluno.cpf }} <br><br>
            <b>Email:</b> {{ aluno.email }} <br><br>
            <b>Data de Nascimento:</b> {{ aluno.nascimento }} <br><br>
            <b>Telefone:</b> {{ aluno.telefone }} <br><br>
            <b>Endereço:</b> {{ aluno.endereco }} <br><br>
            {% if aluno.altura is None %}
            <b>Altura:</b> <br><br>
            {% else %}
            <b>Altura:</b> {{ aluno.altura }} cm <br><br>
            {% endif %}
            {% if aluno.peso is None %}
            <b>Peso:</b> <br><br>
            {% else %}
            <b>Peso:</b> {{ aluno.peso }} kg <br><br>
            {% endif %}
            {% if aluno.bracos is None %}
            <b>Braços:</b> <br><br>
            {% else %}
            <b>Braços:</b> {{ aluno.bracos }} cm <br><br>
            {% endif %}
            {% if aluno.coxa is None %}
            <b>Coxa:</b> <br><br>
            {% else %}
            <b>Coxa:</b> {{ aluno.coxa }} cm <br><br>
            {% endif %}
            {% if aluno.peitoral is None %}
            <b>Peitoral:</b> <br><br>
            {% else %}
            <b>Peitoral:</b> {{ aluno.peitoral }} cm <br><br>
            {% endif %}
            {% if aluno.cinturaescapular is None %}
            <b>Cintura escapular:</b> <br><br>
            {% else %}
            <b>Cintura escapular:</b> {{ aluno.cinturaescapular }} cm <br><br>
            {% endif %}
            {% if aluno.percentualgordura is None %}
            <b>Percentual de gordura:</b> <br><br>
            {% else %}
            <b>Percentual de gordura:</b> {{ aluno.percentualgordura }} % <br><br>
            {% endif %}
        </ul>
    </div>
    <br><br>
    <a href="{% url 'alunos:home' %}" class="btn btn-secondary">Voltar</a>
    <br><br>

{% endblock %}