USPesos/urls.py
from django.contrib import admin
from django.urls import path, include
from user.views import login2

urlpatterns = [
    path('', login2 ,name='login_redirect'),
    path('user/', include('user.urls')),
    path('alunos/', include('alunos.urls')),
    path('professores/', include('professores.urls')),
    path('secretaria/', include('secretaria.urls')),
    path('user/', include('django.contrib.auth.urls')),
    path('admin/', admin.site.urls),
    path('api/v1/', include('api.urls')),
]

api/urls.py
from django.urls import path
from .views import ExercicioList, ExercicioDetail

urlpatterns = [
    path('exercicios/<int:pk>/', ExercicioDetail.as_view()),
    path('exercicios/', ExercicioList.as_view())
]

professores/urls.py
from django.urls import path
from . import views

# URLs dos usuários

app_name = 'professores'

urlpatterns = [
    path('home/',views.home, name = 'home'),
    path('solicitacoes/',views.solicita_treino, name = 'solicitacoes'),
    path('nova_aula/', views.AdicionaAula.as_view(), name = 'nova_aula'),
    path('aulas/', views.aulas, name = 'aulas'),
    path('solicitacoes/<int:pk>/',views.mostra_treino, name = 'mostra_treino'),
    path('solicitacoes/<int:pk>/add',views.treino_add_ex, name = 'add_ex_treino'),
    path('solicitacoes/<int:pk>/delete/<int:pk2>/',views.treino_deleta_ex, name = 'deleta_ex_treino'),
    path('solicitacoes/<int:pk>/send',views.manda_treino, name = 'manda_treino'),
    path('aulas/<int:pk>/vis',views.visivel, name = 'aula_visivel'),
    path('aulas/<int:pk>/det',views.detalhe_aula, name = 'detalhe_aula'),
    path('aulas/<int:pk>/delete',views.DeletarAula.as_view(), name = 'deletar_aula'),
]

professores/models.py
from django.db import models
from user.models import Aluno, Professor 

# Create your models here.

class Exercicio(models.Model):

    nome = models.CharField("Nome do exercício", blank=True, max_length= 255)
    urlfoto = models.CharField("URL da imagem do exercicio", blank=True, max_length= 255)
    maquina = models.CharField("Nome da máquina", blank=True, max_length= 255)


    def __str__(self):
        return self.nome + ' (' + self.maquina + ')'

class Treino(models.Model):

    # Itens próprios do treino
    nivel = models.IntegerField("Nível de dificuldade", blank=True)
    comentario = models.TextField("Comentários", blank = True)
    criado = models.BooleanField("Já foi montado?", blank= True, default = False)

    # Aluno e Professor envolvidos
    aluno = models.ForeignKey(Aluno, on_delete= models.CASCADE)
    professor = models.ForeignKey(Professor, on_delete= models.CASCADE)

    def __str__(self):
        return 'treino de ' + self.aluno.user.name

class Itemtreino(models.Model):

    # Itens próprios do item treino
    carga = models.IntegerField("Carga do exercício", blank=True)
    repeticao = models.IntegerField("Número de repetições", blank=True)

    # Relação
    treino = models.ForeignKey(Treino, on_delete= models.CASCADE)
    exercicio = models.ForeignKey(Exercicio, on_delete= models.CASCADE)

    def __str__(self):
        return self.exercicio.nome

class Modalidade(models.Model):
    nome = models.CharField("Nome da modalidade", blank = True, max_length= 255)
    descricao = models.TextField("Descrição da modalidade", blank = True)

    def __str__(self):
        return self.nome 

class Aula(models.Model):

    # Itens próprios
    dia = models.DateField("Dia da aula", blank = True)
    hora = models.TimeField("Horário da aula", blank = True)
    duracao = models.TimeField("Duração da aula", blank = True, default=0)
    vagas = models.IntegerField("Número de vagas", blank = True , default=0)
    visivel = models.BooleanField("Visível", blank=True)
    inscritos = models.IntegerField("Número de inscritos", blank = True , default=0)

    # Relação
    professor = models.ForeignKey(Professor, on_delete=models.CASCADE)
    modalidade = models.ForeignKey(Modalidade, on_delete=models.CASCADE)

    def __str__(self):
        return self.modalidade + ' do ' + self.professor.user.name

class Inscricao(models.Model):

    aula = models.ForeignKey(Aula, on_delete=models.CASCADE)
    alunos = models.ManyToManyField(Aluno, blank = True)

    def __str__(self):
        return 'inscricao de aula' + self.aula.modalidade.nome

professores/forms.py
from django import forms
from django.forms import ModelForm
from .models import Aula, Inscricao, Itemtreino
from django.db import transaction


class DateInput(forms.DateInput):
    input_type = 'date'

class AulaForm(ModelForm):
    class Meta:
        model = Aula
        fields = [
            'modalidade',
            'dia',
            'hora',
            'duracao',
            'vagas',
        ]
        widgets = {
            'dia': DateInput(),
            'hora': forms.TimeInput(attrs={'type': 'time'}),
            'duracao': forms.TimeInput(attrs={'type': 'time'}),
        }


class ItemTreinoForm(ModelForm):
    class Meta:
        model = Itemtreino
        fields = ('carga', 'repeticao', 'exercicio', )

professores/views.py
from django.shortcuts import render, get_list_or_404, get_object_or_404, redirect
from django.http import HttpResponse
from user.models import Professor
from .models import Treino, Itemtreino, Aula, Inscricao, Exercicio
from .forms import AulaForm, ItemTreinoForm
from django.views.generic import UpdateView, CreateView, DeleteView
from django.contrib.auth.decorators import login_required
from user.decorators import professor_required
from django.utils.decorators import method_decorator

# Create your models here.

@login_required
@professor_required
def home(request):
    professor = Professor.objects.get(user=request.user)
    context = {'professor' : professor,}
    return render(request, 'professores/home.html', context = context)

@login_required
@professor_required
def solicita_treino(request):

    professor = Professor.objects.get(user=request.user)
    solicitacoes = Treino.objects.filter(professor = professor).filter(criado = False).all()

    context = {
        'professor' : professor,
        'solicitacoes' : solicitacoes,
    }

    return render(request, 'professores/solicitacoes.html', context = context)

@login_required
@professor_required
def mostra_treino(request, pk):

    treino = get_object_or_404(Treino, pk = pk, professor = Professor.objects.get(user = request.user))
    itenstreino = Itemtreino.objects.filter(treino = treino).all()

    context = {
        'itenstreino' : itenstreino,
        'pk' : pk,
        'treino' : treino,
    }

    return render(request, 'professores/solicitacao.html', context= context)

@login_required
@professor_required
def manda_treino(request, pk):

    treino = get_object_or_404(Treino, pk = pk, professor = Professor.objects.get(user = request.user))
    treino.criado = True
    treino.save()

    return redirect('professores:solicitacoes')

@login_required
@professor_required
def treino_add_ex(request, pk):

    treino = get_object_or_404(Treino, pk = pk, professor = Professor.objects.get(user = request.user))


    if request.method == 'POST':

        form = ItemTreinoForm(request.POST)

        if form.is_valid():
            itens_treino = form.save(commit=False)
            itens_treino.treino = treino
            itens_treino.save()

        return redirect('professores:mostra_treino', pk)

    else:

        form = ItemTreinoForm()

    return render(request, 'professores/montar.html', { 'treino' : treino, 'form' : form })

def treino_deleta_ex(request, pk, pk2):
    
    item_treino = get_object_or_404(Itemtreino, pk = pk2)
    treino = item_treino.treino
    pk3 = item_treino.treino.pk
    item_treino.delete()

    return redirect('professores:mostra_treino', pk3)



@method_decorator([login_required, professor_required], name='dispatch')
class AdicionaAula(CreateView):
    model = Aula
    form_class = AulaForm
    template_name = 'professores/nova_aula.html'
    success_url = '/professores/aulas'

    def form_valid(self, form):

        aula = form.save(commit=False)

        aula.professor = Professor.objects.get(user = self.request.user)
        aula.visivel = False

        aula.save()

        inscricao = Inscricao.objects.create(aula = aula)

        inscricao.save()
        return redirect('professores:aulas')

@login_required
@professor_required
def aulas(request):

    aulas = Aula.objects.all().filter(professor = Professor.objects.get(user = request.user))
    professor = Professor.objects.get(user = request.user)

    context = {
        "aulas" : aulas,
        "professor" : professor,
    }

    return render(request, 'professores/aulas.html', context = context)

@login_required
@professor_required
def visivel(request, pk):
    aula = get_object_or_404(Aula, pk = pk, professor = Professor.objects.get(user = request.user))

    if aula.visivel:
        aula.visivel = False
    else:
        aula.visivel = True
    
    aula.save()

    return redirect('professores:aulas')

@login_required
@professor_required
def detalhe_aula(request, pk):

    aula = get_object_or_404(Aula, pk = pk)

    alunos = Inscricao.objects.get(aula = aula).alunos.all()

    context = {
        'aula' : aula,
        'alunos' : alunos,
    }

    return render(request, 'professores/detalhe_aula.html', context= context)

@method_decorator([login_required, professor_required], name='dispatch')
class DeletarAula(DeleteView):
    model = Aula
    success_url = '/professores/aulas'
    template_name = 'professores/deletaraula.html'

professores/templates/professores/aulas.html
{% extends 'base.html' %}

{% block title %}
Aulas
{% endblock title %}

{% block content %}

<div class="d-flex justify-content-around">
    <div class = "p1"><h1>Aulas</h1></div>
    <div style="width: 70%"></div>
    <div class = "p2"><a href="{% url 'professores:nova_aula' %}" class="btn btn-primary" style="height:40px;"><b>Adicionar</b></a></div>
</div>
    <br>

{% if aulas %}
    <div class = "lista-aulas">
    {% for aula in aulas %}
        <div class = "card-aulas">
            <h5 style="text-align: center; margin-top: 10px; color: white;"><b>Aula de {{ aula.modalidade }}</b></h5>
            <p style="text-align: center;">Dia {{ aula.dia }}</p>
            <div style="text-align: center;">
                <a href="{% url 'professores:detalhe_aula' aula.pk %}" class="btn btn-secondary">Ver detalhes</a>
            </div>
            <br>
            <br>

            <div class="d-grid gap-2 col-6 mx-auto">   
                <a href="{% url 'professores:aula_visivel' aula.pk %}" class="btn btn-secondary"> visivel/invisível </a>
            </div>

            {% if aula.visivel %}
            <p class="p1" style="text-align: center;"> A aula está <b><u style="color: rgb(254, 185, 47);">visível</u></b></p>

            {% else %}
            <p class="p1" style="text-align: center;"> A aula está <b><u>invisível</u></b></p>

            {% endif %}

            <br>
            <div class="d-grid gap-2 col-6 mx-auto">
                <a href = "{% url 'professores:deletar_aula' aula.pk %}" class="btn btn-danger">Apagar</a>
            </div>

        </div>
    {% endfor %}
    </div>

{% else %}
    <div class = "p1"><p>Não há nenhuma aula cadastrada.</p></div>
{% endif %}
<p>

</p>

<br>
<br>

<a href="{% url 'professores:home' %}" class="btn btn-secondary">Voltar</a>
    
<br>
<br>

{% endblock %}

professores/templates/professores/deletaraula.html
{% extends 'base.html' %}

{% block title %}
Home
{% endblock title %}

{% block content %}

<form method="post">{% csrf_token %}
     
 
 
 
    <p>Tem certeza que quer deletar a aula ?</p>
     
     
     
     
    <input type="submit" value="Confirm">


    <br>
    <br>
    <a href="{% url 'professores:aulas' %}">Cancelar</a>
</form>

{% endblock %}

professores/templates/professores/detalhe_aula.html
{% extends 'base.html' %}

{% block title %}
Aula de {{ aula.modalidade }}
{% endblock title %}

{% block content %}

<h1 class="p1"> Aula de {{ aula.modalidade }} </h1>
<br>

<ul class="p1">
    <li> <u><b>Modalidade:</b></u> {{ aula.modalidade.nome }} </li>
    <li> <u><b>Descrição:</b></u> {{ aula.modalidade.descricao }} </li>
    <li> <u><b>Capacidade:</b></u>  {{ aula.inscritos }} / {{ aula.vagas }}</li>
    <li> <u><b>Horário:</b></u> {{ aula.hora }} </li>
    <li> <u><b>Duração:</b></u> {{ aula.duracao }} </p>  
</ul>

{% if alunos %}

    <p> Lista de alunos inscritos: </p>

    {% for aluno in alunos %}
            
    <p> {{ aluno }}</p>

    {% endfor %}


{% else %}

<p class="p1">Não há alunos inscritos ainda</p>

{% endif %}

<br>
<br>

<a href="{% url 'professores:aulas' %}" class="btn btn-secondary">Voltar</a>
    
<br>
<br>

{% endblock %}

professores/templates/professores/home.html
{% extends 'base.html' %}

{% block title %}
Home
{% endblock title %}

{% block content %}



    <div class="d-flex justify-content-around">
      <div class = "p1"><h1>Olá, {{ user.name }}!</h1></div>
      <div style="width: 55%"></div>
      <div class = "p2" class="text-decoration-none">
        <div class="text-center">
            <img src="{{ professor.urlfoto }}" alt="Foto de perfil" id="foto-perfil">
            <br>
            <p>{{ user.name }}</p>
        </div>
      </div>
    </div>

<br>

<div class="d-flex justify-content-around">

    <div style="width: 10px;"></div>

    <a href="{% url 'professores:solicitacoes' %}" id="foto-container">
        <div class="card bg-dark text-white">
        <img src="/static/meu_treino.jpg" class="d-block w-100 brilho-50" alt="Meu treino">
        <div class="card-img-overlay">
          <h1 class="card-title text-center">Montar Treino</h1>
        </div>
      </div>
    </a>

    <div style="width: 10px;"></div>

    <a href="{% url 'professores:aulas' %}" id="foto-container">
      <div class="card bg-dark text-white">
        <img src="/static/aulas.webp" class="d-block w-100 brilho-30" alt="Aulas">
        <div class="card-img-overlay">
            <h1 class="card-title text-center">Cadastrar Aulas</h1>
        </div>
      </div>
    </a>

    <div style="width: 10px;"></div>
      
</div>


{% endblock %}

professores/templates/professores/montar.html
{% extends 'base.html' %}

{% block title %}
Montar treino
{% endblock title %}

{% block content %}

<div id = "tp">
    <div class = "p1"><h1><p style="color: white;">Adicionar um exercício</p></h1></div>  
</div>
<br>

<div>
    <div class = "p1">
        <form method="post" novalidate>
            {% csrf_token %}
            {{ form.as_p }}
            <button type="submit" class="btn btn-success">Save</button>
        </form>
        <br>
        <br>
        <a href="{% url 'professores:mostra_treino' treino.pk %}">Cancelar</a>
    </div>
</div>



{% endblock %}

professores/templates/professores/nova_aula.html
{% extends 'base.html' %}

{% block title %}
Nova aula
{% endblock title %}

{% block content %}

<div id = "tp">
    <div class = "p1"><h1><p style="color: white;">Criar uma nova aula</p></h1></div>  
</div>
<br>

<div class = "p1">
    <form method="POST" action="{% url 'professores:nova_aula' %}">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit" class="btn btn-primary">Criar</button>
    </form>
</div>

<br>
<br>

<a href="{% url 'professores:aulas' %}" class="btn btn-secondary">Voltar</a>
    
<br>
<br>
{% endblock %}

professores/templates/professores/solicitacao.html
{% extends 'base.html' %}

{% block title %}
Criar Treino
{% endblock title %}

{% block content %}

<div class="d-flex justify-content-around">
    <div class = "p1"><h1>Solicitação de treino</h1></div>
    <div style="width: 60%"></div>
    <div class = "p2"><a href = "{% url 'professores:manda_treino' pk %}" class="btn btn-success" style="height:40px;"><b>Enviar</b></a></div>
</div>
    <br>

{% if itenstreino %}
    <div class = "lista-exercicio">
    {% for item in itenstreino %}
        <div class = "card-exercicio">
            <p> <b>Exercício:</b> {{ item.exercicio }}</p>
            <p> <b>Carga:</b> {{ item.carga }} Kg</p>
            <p> <b>Repetições:</b> {{ item.repeticao }}</p>
            <p><img src="{{ item.exercicio.urlfoto }}" alt="Foto do exercicio" id="foto-exercicio"> </p>
            <div class="d-grid gap-2 col-6 mx-auto">
                <a href = "{% url 'professores:deleta_ex_treino' pk item.pk %}" class="btn btn-danger">Deletar item</a>
            </div>
        </div>

        <br>
    {% endfor %}
    </div>
{% else %}

{% endif %}
    <hr>
        <a href = "{% url 'professores:add_ex_treino'  pk  %}" class="btn btn-primary">Adicionar um novo exercício</a>
        <br><br>
        <br>
        <br>

        <a href="{% url 'professores:solicitacoes' %}" class="btn btn-secondary">Voltar</a>
            
        <br>
        <br>

{% endblock %}

professores/templates/professores/solicitacoes.html
{% extends 'base.html' %}

{% block title %}
Home
{% endblock title %}

{% block content %}

<div id = "tp">
    <div class = "p1"><h1><p style="color: white;">Solicitações de treino</p></h1></div>  
</div>
<br>
{% if solicitacoes %}
    <div class = "lista-solicitacoes">
    {% for solicitacao in solicitacoes %}
        <div class = "card-solicitacoes">
            <p style="text-align: center; border-bottom: 3px solid white; border-top-left-radius: 10px; border-top-right-radius: 10px; padding: 10px; background-color: black;">Solicitação do aluno <b>{{ solicitacao.aluno.user.name}}</b> de <b>nível {{ solicitacao.nivel }}</b></p>
            <div style="background-color: rgb(55, 55, 55); border-left: 20px solid rgb(55, 55, 55); border-right: 20px solid rgb(55, 55, 55); padding-left: 10px;" >
                <p style="color:rgb(255, 255, 255)">Comentário do aluno: 
                    <br>"{{ solicitacao.comentario }}"</p><br>
                <div class="d-grid gap-2 col-6 mx-auto">
                    <a href="{% url 'professores:mostra_treino' solicitacao.pk %}" class="btn btn-primary">Editar</a>
                </div>
            </div>
            
        </div>
    {% endfor %}
    </div>
    <br>
{% else %}
    <p class="p1">Não há solicitações pendentes.</p>
{% endif %}
    
<br>
<br>

<a href="{% url 'professores:home' %}" class="btn btn-secondary">Voltar</a>
    
<br>
<br>

{% endblock %}